#! /bin/sh

xrdb .Xresources &
picom &
polybar -r top &
polybar -r bottom &
feh --bg-fill ~/Pictures/wallpaper.jpg &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
